### ISSUE TITLE
Why call abort and not exit?

### ISSUE THREAD

**Issue by simon-p-r** [daddinuz/liblogger#1]
Hi

I like your library however calling abort doesn't seem right as caller has no control.  I can do a PR if you agree.

Thanks

**Comment by daddinuz** [comment]
Hi 

yes, calling abort really sucks, anyway I don't think exit is a better solution.
Right now there isn't a real error  handling policy, I will take the next days to choose one.

Thank you.

**Comment by daddinuz** [comment]
I'm going to mark this repository as deprecated so I decided to not change the way in which error handling is performed, anyway I made a new logging library with a better error handling and better output customizations, should not be too hard to move the existing code to the new library.

I apologize for any inconvenience this might cause.
