### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by simon-p-r** [daddinuz/liblogger#2]
Hi

I called function stream_logger_new with NULL param for identifier however when I called delete it frees char without checking if it is NULL causing crash.   Can the identifier be prefixed with something different instead of () such as [ ]?  I cannot see where this is set, sorry for the questions but I am new to c.

Thanks again

**Comment by daddinuz** [comment]
Hi

I'm going to fix the logger_delete crash as soon as possible, concerning the identifiers instead, right now is not possible to specify any kind of formatter, so I'm going to open an enhancement request for this feature.

Thank you for reporting :smiley:

**Comment by daddinuz** [comment]
> Can the identifier be prefixed with something different instead of () such as [ ]?

@simon-p-r  I tried to change the code in order to support some kind of custom formatting feature, but I ended up in rewriting the whole library. It's still a work in progress but you can checkout the code here: https://github.com/daddinuz/logger
